### ISSUE TITLE
Error while unzipping and reading cgMLST alleles

### ISSUE THREAD

**Issue by dfornika** [WGS-TB/MentaLiST#29]
After downloading a cgMLST `alleles` zip file and opening it via `GZip.open()` we try to iterate over the resulting `GZip.GZipStream`.

https://github.com/WGS-TB/MentaLiST/blob/0594e74aca4e9875e120cd1a4dcf7b7da3d7ac0a/src/mlst_download_functions.jl#L191-L203

https://travis-ci.org/WGS-TB/MentaLiST/jobs/358091615#L1184-L1201

**Comment by dfornika** [comment]
The cgMLST server returns a `.zip` file, but we're using a `GZip` library. Has the format of the cgMLST file changed?

http://www.cgmlst.org/ncs/schema/1025099/alleles/

**Comment by dfornika** [comment]
Was cgMLST serving a single large gzipped fasta file? That's what it looks like based on the current code.

**Comment by pedrofeijao** [comment]
Yes, it was. Apparently they changed it to zip.

**Comment by dfornika** [comment]
The fix has been merged into the `master` and `mentalist_v0.2` branches.
