### ISSUE TITLE
Can't download M. tuberculosis schemes from cgMLST

### ISSUE THREAD

**Issue by dfornika** [WGS-TB/MentaLiST#4]
User [Daniel Kein](https://github.com/dankein) (daniel.kein@canada.ca) reports:

I can’t get the cgMLST schema for M. tuberculosis installed. M. tuberculosis is not present when I run the command: MentaLiST.jl list_cgmlst
I think this is probably because they recently changed the name and added a bunch of /’s ([Mycobacterium tuberculosis/bovis/africanum/canettii cgMLST](http://www.cgmlst.org/ncs/schema/741110/)). The same problem exists for ([Klebsiella pneumoniae/variicola/quasipneumoniae](http://www.cgmlst.org/ncs/schema/2187931/) cgMLST).

**Comment by dfornika** [comment]
Looks like the regex on [this line](https://github.com/WGS-TB/MentaLiST/blob/2334912348778286fe0ff795fff002c3611bce79/src/mlst_download_functions.jl#L98) will need to accept `/` characters in the species name.

**Comment by dfornika** [comment]
Current output of `list_cgmlst` before fix:

```
#id	organism
3956907	Acinetobacter baumannii       
3560802	Clostridioides difficile      
991893	Enterococcus faecium          
260204	Francisella tularensis        
1025099	Legionella pneumophila        
690488	Listeria monocytogenes        
141106	Staphylococcus aureus
```

**Comment by pedrofeijao** [comment]
Hi Dan,
I decided to be more general in case they add some strange characters in the name. Just get everything between the two <em> </em>. That is the problem of automatically parsing pages that are not supposed to be automatically parsed, we might have to check from time to time if things are still working.
