### ISSUE TITLE
Missing R dependency for mentalist_distance Galaxy tool

### ISSUE THREAD

**Issue by apetkau** [WGS-TB/MentaLiST#62]
It looks like the `mentalist_distance` Galaxy tool is missing a dependency on R (https://github.com/WGS-TB/MentaLiST/blob/v0.1.8/galaxy/tools/mentalist_distance/mentalist_distance.xml#L1).  R must have already been installed in Docker so I missed it during tests, but on our cluster this causes issues.

Since the package `r` is already in conda, I think it should just be a matter of adding the dependency to the Galaxy tool and it should all work.

**Comment by dfornika** [comment]
I've pushed an updated tool to the Test Toolshed: https://testtoolshed.g2.bx.psu.edu/view/dfornika/mentalist/1f765046e008

I'm just checking that it installs properly in my development environment then I'll push to the main toolshed.
