### ISSUE TITLE
Incorrect allele designation

### ISSUE THREAD

**Issue by nickloman** [WGS-TB/MentaLiST#77]
I just ran a bunch of MLST assignments on a Pseudomonas aeruginosa reads - I found a large number of unexpected single locus variants. Unexpected they share the same allele number for 'acs' which was 205. I was suspicious that this was an error because that allele number came up across diverse isolates in my dataset with otherwise very different profiles. On inspection acs:205 is the last entry in the P. aeruginosa FASTA file. Therefore I suspect there is some kind of bug that means that the last allele profile number is selected (perhaps when the correct allele cannot be determined). Hopefully this is enough information to track down but please let me know if you need any more data.

**Comment by nickloman** [comment]
Never mind, it was some background contamination in my read data causing this problem.

**Comment by dfornika** [comment]
😓
