### ISSUE TITLE
PackagesNotFoundError: mentalist not available from current channels

### ISSUE THREAD

**Issue by smoretti** [WGS-TB/MentaLiST#84]
Hi

I try to install MentaLiST on Linux but every time I try the conda command in the README.md file, or the ones from https://anaconda.org/bioconda/mentalist I get the same issue: PackagesNotFoundError

mentalist is never found as well as julia but sometimes this is *julia==0.5.2* that is not found, sometimes *julia=0.6.1*.

I have already installed packages with conda without any issues.
I use conda 4.5.12 on CentOS 7.

```
$ conda install  -c bioconda mentalist --prefix=$PWD
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mentalist
  - julia==0.5.2

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

...
```

**Comment by dfornika** [comment]
Hi @smoretti , thanks for your interest in using MentaLiST.

I think there are a couple of issues here. I noticed that you don't have the `conda-forge` channel enabled. The `julia` package is supplied by that channel. Our installation instructions should be more clear, so we'll update that soon.

Unfortunately, we're having some ongoing issues getting a stable conda installation (see #83) so I wouldn't recommend using conda to install MentaLiST at the moment.

If possible, I'd recommend installing `julia-0.6.4` using one of the official binaries from the julia site:

https://julialang.org/downloads/oldreleases.html

...Then clone the `MentaLiST` repo and install the julia package dependencies as described in our macOS installation instructions:

https://github.com/WGS-TB/MentaLiST#macos-108

Would this be an acceptable work-around for your system?

**Comment by dfornika** [comment]
I suspect you'll have trouble with the docker container, unfortunately. It's built from the bioconda recipe, so it will likely have all the same issues that the bioconda recipe has. In fact there are some issues with the way julia compiles code that have made it difficult to produce a working docker container even when the bioconda recipe has been working.
