### ISSUE TITLE
--fasta argument not recognized

### ISSUE THREAD

**Issue by stefcardinale** [WGS-TB/MentaLiST#88]
I installed the program manually and it seems to work just fine until I run the 'call' option on a fasta file (a genome sequence) as input. I am not sure whether I should input the file as -1 argument or not, but I give the argument --fasta, however I get the following error:
ERROR: LoadError: UndefVarError: fastq_file not defined

Not sure what is happening, any help?

**Comment by pedrofeijao** [comment]
Thanks for reporting this issue @stefcardinale . It was a simple bug, it is fixed and I've already pushed the fix on the master branch. You can pull the new version and try again.
